### PR TITLE
Add VDP link to footer

### LINKED ISSUE #215: DOE VDP info in footer
The US Department of Energy wants public-facing DOE webpages to have following text and link as part of their footer.

>Learn about the Department of Energy’s [Vulnerability Disclosure Program](https://doe.responsibledisclosure.com/hc/en-us)

More on VDP:

>VDP (Vulnerability Disclosure Program) is a centralized channel for the public to responsibly disclose vulnerabilities found in good faith and a centralized process and set of resources dedicated to vulnerability disclosure validation, triage, and routing for the enterprise.

### PR DESCRIPTION
**Pull request by mauzey1**
Resolves #215 
Screenshot 2022-05-09 at 11-32-11 CDAT

### CODE REVIEW

**Comment by mauzey1** [comment]
@downiec please review and merge

**Comment by sashakames** [comment]
@mauzey1 Hi Chris, Carlos is no longer working on CDAT.  Tom would be an appropriate person, as he's the lead XCDAT developer, but needs to be added to this repo.

**Comment by mauzey1** [comment]
@sashakames I don't have permissions to add new members or merge PRs for this repo.  Who else can I get to approve and merge this PR?

**Comment by sashakames** [comment]
Looks like @jasonb5 is part of the CDAT org, perhaps he can help, thanks, Jason.

**Pull request merged**
